<div class="example">
    <audio controls preload="auto" crossorigin style="width: 100%;">
        <source src="<?php echo $wo['media']['filename']; ?>" type="audio/mpeg">
        <source src="<?php echo $wo['media']['filename']; ?>" type="audio/mp3">
    </audio>
</div>

<style>
    /* .mejs-container {
	width: 100% !important;
	margin-left: auto;
    margin-right: auto;
} */

</style>
<script>
    //$('audio').mediaelementplayer();
    document.addEventListener('DOMContentLoaded', function() {
      new GreenAudioPlayer('.example');
    });
    
</script>